name: euclido
services:
    postgres:
        container_name: postgres-container
        image: postgres:16
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pLSkczmWBHK0CVh
            - POSTGRES_DB=event-management
        ports:
            - '5432:5432'
        volumes:
            - /home/ubuntu/pg-data:/var/lib/postgresql/data/:rw
            - ./sql/prod-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    redis:
        container_name: redis-container
        image: redis
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - /home/ubuntu/redis-data:/data

    event-management-app:
        container_name: event-management-app
        ports:
            - 3000:3000
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
            target: production
        image: event-management-app
        environment:
            - APP_ENV=development
            - APP_PORT=3000
            - APP_URL=http://localhost:3000

            # DEVELOPMENT ENVIRONMENT
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME=postgres
            - DB_PASSWORD=pLSkczmWBHK0CVh
            - DB_NAME=event-management

            #SMTP CONFIG
            - SMTP_HOST=smtp-relay.brevo.com
            - SMTP_USER=mohaiminuliraj@gmail.com
            - SMTP_PASSWORD=xsmtpsib-66931eda740cae0c47fc303762abe6b7bebdd961fea71db5c17797b827d99331-CXAWsJwGDT5vrEVh
            - SMTP_MAIL_FROM=mohaiminuliraj@gmail.com
            - SMTP_PORT=587

            # REDIS CONFIG
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - TTL=3600 #SECONDS

            #MISC
            - RATE_LIMITER_TIME_TO_LEAVE=6000 #MILLISECONDS
            - RATE_LIMITER_MAX_TRY=60
        user: 'appuser:appgroup' # Explicitly set the user
        depends_on:
            - postgres
            - redis
